# Generated by Django 4.2 on 2023-04-13 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, default='Private', max_length=40, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('interested_in', models.CharField(blank=True, default='All plants', max_length=140, null=True)),
                ('avatar', models.ImageField(blank=True, default='../default_avatar_zf68aj', upload_to='images/')),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_on'],
            },
        ),
    ]
