# Generated by Django 4.2 on 2023-06-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='messages',
        ),
    ]
