# Generated by Django 4.2 on 2023-05-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Taken')], default='Available'),
        ),
    ]
