# Generated by Django 4.2 on 2023-05-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='../default_plant_xc6ngh.png', upload_to='images/'),
        ),
    ]
