# Generated by Django 4.2 on 2023-06-06 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0007_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='ad_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
