# Generated by Django 4.2 on 2023-05-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
